lowercaseOutputName: true
rules:
  # 1. Message
  - pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)><>Count
    name: kafka_server_messages_in_total
    labels:
      topic: "$1"

  # 2. Partition health (UnderReplicated - shoud always be = 0)
  - pattern: kafka.server<type=ReplicaManager, name=UnderReplicatedPartitions><>Value
    name: kafka_server_under_replicated_partitions

  # 3. Consumer Lag
  - pattern: kafka.server<type=FetcherLagMetrics, name=ConsumerLag, clientId=(.+), topic=(.+), partition=(.+)><>Value
    name: kafka_server_consumer_lag
    labels:
      client_id: "$1"
      topic: "$2"
      partition: "$3"